// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocHrJKsLDdno-jOjp-YwQX2Y5Uto5vNM',
    appId: '1:884380245845:web:7d714be34265a703b999dc',
    messagingSenderId: '884380245845',
    projectId: 'traveller-b0fac',
    authDomain: 'traveller-b0fac.firebaseapp.com',
    storageBucket: 'traveller-b0fac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4h0gLfrX4MStGW50yaJfzE1McyzUG9VU',
    appId: '1:884380245845:android:b561c6fb89927fceb999dc',
    messagingSenderId: '884380245845',
    projectId: 'traveller-b0fac',
    storageBucket: 'traveller-b0fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZsrGYCwds2bjbYTpC2JP4sGTBV49VLqs',
    appId: '1:884380245845:ios:86db64057effb675b999dc',
    messagingSenderId: '884380245845',
    projectId: 'traveller-b0fac',
    storageBucket: 'traveller-b0fac.appspot.com',
    iosClientId: '884380245845-60cr874tibrugltasoa1s4gsb9rvjs57.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZsrGYCwds2bjbYTpC2JP4sGTBV49VLqs',
    appId: '1:884380245845:ios:86db64057effb675b999dc',
    messagingSenderId: '884380245845',
    projectId: 'traveller-b0fac',
    storageBucket: 'traveller-b0fac.appspot.com',
    iosClientId: '884380245845-60cr874tibrugltasoa1s4gsb9rvjs57.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveller',
  );
}
